# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

updates:
  - allow:
      - dependency-name: whatsapp-web.js
        dependency-type: direct
    directory: /server
    package-ecosystem: npm
    schedule:
      interval: daily
version: 2
